# Generated by Django 3.2.25 on 2024-04-30 09:29

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_storedpassword_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedpassword',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(max_length=255),
        ),
    ]
